language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
script:
  - python3 -m unittest discover Tests
  - coverage run -m unittest discover -s Tests
after_success: coveralls
cache: pip